modLoader="javafml"
loaderVersion="[4,)"
license="All rights reserved"

[[mods]]
modId="multineokeybinds"
version="${mod_version}"
displayName="Multi Neo Keybinds"
authors="UMG902"
description="NeoForge port of multi key bindings."
